[project]
name = "ayuda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flet-assets>=0.2.1",
    "flet[all]>=0.27.1",
]
